consul:
    image: gaikai/alpn-consul:supervisor
    hostname: consul
    container_name: consul
    ports:
     - 8500
    environment:
     - DC_NAME=dc1
     - CONSUL_BOOTSTRAP_EXPECT=1
    dns: 127.0.0.1

influxdb:
    hostname: influxdb
    container_name: influxdb
    image: qnib/influxdb
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
     - SENSU_SERVER=false
     - SENSU_CLIENT=false
     - SENSU_API=false
    volumes:
     - /opt/influxdb/shared
    links:
     - consul:consul
    ports:
     - 4242:4242
     - 8083:8083
     - 8086:8086

grafana2:
    hostname: grafana2
    container_name: grafana2
    image: qnib/grafana2
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
     - GRAFANA_DEFAULT_SOURCE=influxdb
     - SENSU_SERVER=false
     - SENSU_CLIENT=false
     - SENSU_API=false
    ports:
     - "3000:3000"
    volumes:
     - ./opt/qnib/grafana/dashboards/:/opt/qnib/grafana/dashboards/
    links:
     - consul:consul
